MEMBROS = [

    "Adla Camilla M. da Silva",
    "Bruno Fonseca Silva Soares", 
    "Carlos Augusto Corrêa",
    "Gabriela Cardoso Brito Carvalho",
    "Giulliana Pivato Campos",
    "Iago de Souza Reis",
    "Iago Lopes Sereno",
    "Isabela Veiga Luchetti Gonçalves",
    "João Carlos Almeida Maciel",
    "Kamilly dos Santos Almeida",
    "Kauã de Oliveira da Silva",
    "Leonardo Antônio Luiz",
    "Liriel Sales Diniz",
    "Luiz Felipe dos Reis Bonatti",
    "Luiz Otávio de Souza Pereira",
    "Luiz Otávio Fernandes de Oliveira",
    "Mariana Loza Santos",
    "Marcos Vinícius de Sousa",
    "Marta Helena Pereira",
    "Mateus Gabriel de Souza",
    "Mateus Hebert Dias Pereira",
    "Nhaumy Laysa S. Januario",
    "Pedro Henrique Onofri Gomes",
    "Rita Helena Ribeiro de Souza",
    "Ronnie Von Luis Júnior",
    "Tiago Freire Elias",
    "Yasmin Camille Zanata de Paula",
    "Yasmin Felizardo Ribeiro"

]